### ISSUE TITLE
Possibily of adding two dots between the numbers.

### ISSUE THREAD

**Issue by AlexNbl27** [dhiyaaulauliyaa/scroll_datetime_picker#5]
I use your package which is very cool to select time (hour and minute) and i would like to add dots between numbers. I don't have time to look at your code but if one day i have i may do a PR.

I also noticed that we can't add a color to text when we have the finger on it (e.g : Samsung clock app)

**Comment by dhiyaaulauliyaa** [comment]
Will consider to add this feature for next release 😊
